from algorithms.base_algorithm import BaseAlgorithm
from algorithms.E00_perfect_algorithm import E00PerfectAlgorithm
from algorithms.E01_simple_algorithm import E01SimpleAlgorithm
from algorithms.E02_simple_algorithm_recalling_mean import (
    E02SimpleAlgorithmRecallingMean,
)
from algorithms.E03_shifted_stories import E03ShiftedStories
from algorithms.E04_loss_fn import E04LossFN
from algorithms.E05_loss_fn_shifted import E05LossFNShifted
